### ISSUE TITLE
Reserve and Pay for Tee Times: Pay with PayPal

### ISSUE THREAD

**Issue by robinneb** [robinneb/golfzing#60]
As a user I want to be able to use PayPal as my form of payment

Tasks: Integrate the PayPal SDK to accept present and future payments. 
Dev please build this in the developer sandbox and do not wait on American Golf to provide official credentials as to not hold up development
The PayPal authentication requirements are - 
- Get an auth code for future payments, using the PayPal Mobile SDK.
- Exchange the auth code for refresh and access tokens, using your back-end server.
- Call the Payments API, using your back-end server.
Get an auth code

1. Confirm that the settings for our REST app on the developer PayPal site includes the Future Payments option.
2. Navigate to the My Apps & Credentials page, and click on your app to edit its settings.
3. In the App Settings section, make sure that Accept Payments is checked. Then, click Advanced options.
4. Check the Future Payments checkbox.

Once a user selects Pay with PayPal button, they will be taken to the PayPal native flow for entering in their credentials and authorizing the payment. At this stage of the transaction, it is being handled entirely by PayPal until authorization is complete. 

The user shall then return to the Golfzing App where they will see that PayPal is the payment platform of choice and shall confirm the payment cost. 

All final payments shall send an email to the user's email on file with a breakdown of the transaction details.

**Comment by drubage** [comment]
Robinne,

As far as I know, the only form of payment we can accept at Golfzing would be a credit card charged via BluePay. EZLinks requires us to send the BluePay token to them at booking so that they can charge a no-show fee if the person does not show up. I don’t think that would be possible via PayPal or Apple Pay and I don’t think they accept any other tokens. I am happy to discuss this further but I really think we can only accept credit cards processed via BluePay.

As a side note, I don’t think the app would be doing any charging at all. You will just send the booking information and credit card info the soon to be developer tee time booking call and we’ll be handling all charges.

[photo]

Drew Michael
VP, Technology, FRUITION
303.416.6943<tel:303.395.1880%20x23> | 303.931.5088<tel:303.931.5088> | drew@fruition.net<mailto:drew@fruition.net> | fruition.net<http://fruition.net/>
201 Fillmore Street Denver, CO 80206
[https://s3.amazonaws.com/images.wisestamp.com/icons/facebook.png]<http://www.facebook.com/fruition?fref=ts> [https://s3.amazonaws.com/images.wisestamp.com/icons/linkedin.png] <http://www.linkedin.com/company/134907?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A2-1-4%2CtarId%3A1428083749602%2Ctas%3Afruition>  [https://s3.amazonaws.com/images.wisestamp.com/icons/twitter.png] <http://twitter.com/FruitionSearch>

Awarded by Inc. 5000 as of one of the nation’s fastest growing private companies.

**Comment by robinneb** [comment]
BluePay's payment gateway supports both PayPal and ApplePay. I think these
are essential mobile booking options so I'd like to plug in to their
services. In both cases (Apple and PayPal), all payments are processed
through Golfzing's BluePay account alongside all other transactions for
uncomplicated reconciliation.

Correct - the app itself never charges but DBG will have to add both
ApplePay and PayPal SDKs into the native apps.

<http://www.redflightmobile.com>
<http://nabpilot.org/challenge/>

**Comment by robinneb** [comment]
@drubage BluePay's payment gateway supports both PayPal and ApplePay. I think these are essential mobile booking options so I'd like to plug in to their services. In both cases (Apple and PayPal), all payments are processed through Golfzing's BluePay account alongside all other transactions for uncomplicated reconciliation.

Correct - the app itself never charges but DBG will have to add both ApplePay and PayPal SDKs into the native apps.
